services:
  - type: web
    name: hearthstone-recovery
    env: node
    buildCommand: npm run render-build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
